spring.application.name=clase_59_jpa

spring.datasource.url=jdbc:mysql://localhost:3306/relaciones
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuracion Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update